[package]
name = "galactic-merchants-guide"
version = "1.0.0"
authors = ["Sebastian Thiel <sthiel@thoughtworks.com>"]
publish = false

[dependencies]

[[bin]]
name="guide"
path="src/main.rs"

[profile.release]
panic = 'unwind'
incremental = false
overflow-checks = true
